name: shopware6-starter
type: shopware6
docroot: public
php_version: "8.2"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.0"
hooks:
    post-start:
        - exec: composer install
        - exec: bin/console user:create admin --password=shopware --admin
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
